name: Irene

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create a directory
        run: mkdir -p irene_yaml

      - name: Create a file
        run: |
          cd irene_yaml
          touch hello.txt
          echo "Hello from GitHub Actions!" > hello.txt
          echo "File created successfully!"
          ls -la
